Plugin version @PLUGIN_VERSION@
<% if (revisionDate) { %>
Revised on ${revisionDate}
<% } %>

${chaptersPlacement.place('before', 'overview')}

<% if (overview) { %>
== Overview

${overview}

<% } %>

${chaptersPlacement.place('after', 'overview')}
${chaptersPlacement.place('before', 'supported_versions')}
<% if (supportedVersions) { %>
== Supported versions
<% if (supportedVersionsText) { %>
$supportedVersionsText
<% } else { %>
The plugin has been tested with the following versions:
<% } %>
<% supportedVersions.each { version -> %>
* ${version}
<% } %>

${chaptersPlacement.place('after', 'supported_versions')}
<% } %>
${chaptersPlacement.place('before', 'prerequisites')}
<% if (prerequisites) { %>
== Prerequisites
${prerequisites}
<% } %>
${chaptersPlacement.place('after', 'prerequisites')}
<% if (configurationProcedure) { %>

== Plugin configurations

Plugin configurations are sets of parameters that can be applied
across some, or all, of the plugin procedures. They
can reduce the repetition of common values, create
predefined parameter sets, and securely store credentials.
Each configuration is given a unique name that is entered
in the designated parameter for the plugin procedures that use them.


=== Creating plugin configurations

To create plugin configurations in {PRODUCT}, complete these steps:

* Go to menu:Administration[Plugins] to open the Plugin Manager.
* Find the @PLUGIN_NAME@ row.
* Click *Configure* to open the
     Configurations page.
* Click *Create Configuration* as per the description of parameters below.

<% if (configurationProcedure.preface) { %>
${configurationProcedure.preface}
<% } %>

=== Configuration procedure parameters

[cols="1a,1a",options="header"]
|===
|Parameter |Description
<% for (def field in configurationProcedure.fields) { %>
|<% if (field.required) { print "__**" } %>${field.name}<% if (field.required) { print "**__" } %> | ${field.documentation}
<% } %>
|===
<% if (configurationProcedure.postface) { %>
${configurationProcedure.postface}
<% } %>
<% } %>

${chaptersPlacement.place('before', 'procedures')}

[[procedures]]
== Plugin procedures

<% if (proceduresPreface) { %>
${proceduresPreface}
<% } %>

<% procedures.each { procedure -> %>
[[${procedure.id}]]
=== ${procedure.name}${procedure.deprecated ? ' (DEPRECATED)' : ''}
<% if (procedure.token) { %>
${procedure.token}
<% } %>
<% if (!procedure.omitDescription && !metadata.omitDescription) { %>
${procedure.description}
<% } %>
<% if (procedure.preface) { %>
${procedure.preface}
<% } %>

==== ${procedure.name} parameters
[cols="1a,1a",options="header"]
|===
|Parameter |Description
<% for (def field in procedure.fields) { %>
| <% if (field.required) { print "__**" } %>${field.name}<% if (field.required) { print "**__" } %> | ${field.documentation?.replaceAll(/[|]/, "\\\\|")}
<% } %>
|===

<% if (procedure.outputParameters != null) { %>

==== Output parameters

[cols="1a,1a",options="header"]
|===
|Parameter |Description
<% for (def param in procedure.outputParameters) { %>
|${param.name} |${param.description?.replaceAll(/\|/, "\\|")}
<% } %>
|===
<% } %>

<% if (procedure.postface) { %>
${procedure.postface}
<% } %>

<% } %>

${chaptersPlacement.place('after', 'procedures')}

${chaptersPlacement.place('before', 'use_cases')}

<% if (useCases) { %>

== Use cases

<% useCases.each { useCase -> %>
${useCase.body}
<% } } %>

${chaptersPlacement.place('after', 'use_cases')}
${chaptersPlacement.place('before', 'known_issues')}
<% if (knownIssues) { %>

== Known issues
${knownIssues}
<% } %>
${chaptersPlacement.place('after', 'known_issues')}

[[rns]]
== Release notes

<% changelog.getOrderedVersions().each { version -> %>
=== ${pluginKey} ${version.version}
<% version.changes.each { change -> %>
- ${change}
<% } %>
<% } %>
